services:
    coreshop.datahub.graphql.querytypegenerator.resource.currency:
        class: CoreShop\Component\Resource\DataHub\QueryType\Resource
        arguments:
            - '@Pimcore\Bundle\DataHubBundle\GraphQL\Service'
            - '@coreshop.data_hub.doctrine_provider'
            - '%coreshop.model.currency.class%'
        tags:
            - { name: pimcore.datahub.graphql.querytypegenerator, id: typegenerator_querydatatype_coreShopCurrency }

    coreshop.datahub.graphql.querytypegenerator.resource.currency.list:
        class: CoreShop\Component\Resource\DataHub\QueryType\ResourceList
        arguments:
            - '@Pimcore\Bundle\DataHubBundle\GraphQL\Service'
            - '@coreshop.data_hub.doctrine_provider'
            - '%coreshop.model.currency.class%'
        tags:
            - { name: pimcore.datahub.graphql.querytypegenerator, id: typegenerator_querydatatype_coreShopCurrencyMultiselect }
