services:
    _defaults:
        public: true

    CoreShop\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelperInterface: '@CoreShop\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper'
    CoreShop\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper:
        lazy: true
        tags:
            - { name: templating.helper, alias: coreshop_currency }

    CoreShop\Bundle\CurrencyBundle\Twig\CurrencyExtension:
        public: false
        arguments:
            - '@CoreShop\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelperInterface'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\CurrencyBundle\Templating\Helper\ConvertCurrencyHelperInterface: '@CoreShop\Bundle\CurrencyBundle\Templating\Helper\ConvertCurrencyHelper'
    CoreShop\Bundle\CurrencyBundle\Templating\Helper\ConvertCurrencyHelper:
        lazy: true
        arguments:
            - '@CoreShop\Component\Currency\Converter\CurrencyConverterInterface'
        tags:
            - { name: templating.helper, alias: coreshop_convert_currency }

    CoreShop\Bundle\CurrencyBundle\Twig\ConvertCurrencyExtension:
        public: false
        arguments:
            - '@CoreShop\Bundle\CurrencyBundle\Templating\Helper\ConvertCurrencyHelperInterface'
        tags:
            - { name: twig.extension }
